---
title: "Model cell-free RNA"
author: "Sanjay Srivatsan and Nick Hasle"
date: "November 21, 2019"
output: html_document
---

```{r setup, include=FALSE}
suppressPackageStartupMessages({
  library(devtools)
  library(SummarizedExperiment)
  library(SingleCellExperiment)
  load_all('../../../bin/monocle3/')
  library(dplyr)
  library(ggplot2)
  library(ggpubr)
  #library(tidyverse)
  library(ggrepel)
  library(Matrix)
  #load_all('Z:/home/haslen/bin/monocle3/')
  source("dispersion_functions.R")
  source('seurat_functions.R')
  DelayedArray:::set_verbose_block_processing(TRUE)
  options(DelayedArray.block.size=1000e7)
})

sessionInfo()
```

## Functions

```{r}
append_umap_coordinates = function(cds){
  colData(cds)$umap1 = cds@reducedDims[["UMAP"]][,1]
  colData(cds)$umap2 = cds@reducedDims[["UMAP"]][,2]
  return(cds)
}

# my version of tidyverse requires that group_by_ is replaced by group_by
estimateDispersionsForCellDataSet =  function(cds, min_cells_detected, removeOutliers, verbose = FALSE)
{
  mu <- NA
  
  progress_opts <- options()$dplyr.show_progress
  options(dplyr.show_progress = T)
  
  cds_pdata <- dplyr::group_by(dplyr::select_(tibble::rownames_to_column(as.data.frame(pData(cds))), "rowname"))
  disp_table <- as.data.frame(disp_calc_helper_NB(cds, cds@expressionFamily, min_cells_detected))
  #disp_table <- data.frame(rowname = row.names(type_res), CellType = type_res)
  
  #message("fitting disersion curves")
  #print (disp_table)
  if(!is.list(disp_table))
    stop("Parametric dispersion fitting failed, please set a different lowerDetectionLimit")
  #disp_table <- do.call(rbind.data.frame, disp_table)
  disp_table <- subset(disp_table, is.na(mu) == FALSE)
  res <- parametricDispersionFit(disp_table, verbose)
  fit <- res[[1]]
  coefs <- res[[2]]
  #removeOutliers = TRUE
  if (removeOutliers){
    CD <- cooks.distance(fit)
    #cooksCutoff <- qf(.99, 2, ncol(cds) - 2)
    cooksCutoff <- 4/nrow(disp_table)
    #print (head(CD[CD > cooksCutoff]))
    #print (head(names(CD[CD > cooksCutoff])))
    message (paste("Removing", length(CD[CD > cooksCutoff]), "outliers"))
    outliers <- union(names(CD[CD > cooksCutoff]), setdiff(row.names(disp_table), names(CD)))
    res <- parametricDispersionFit(disp_table[row.names(disp_table) %in% outliers == FALSE,], verbose)
    fit <- res[[1]]
    coefs <- res[[2]]
  }
  names( coefs ) <- c( "asymptDisp", "extraPois" )
  ans <- function( q )
    coefs[1] + coefs[2] / q
  attr( ans, "coefficients" ) <- coefs
  
  res <- list(disp_table = disp_table, disp_func = ans)
  return(res)
}

```


### Load data

```{r}
# Load Sparse 10x Matrix
path_to_raw_data =
  "../data/cellranger_outputGEO/"

path_to_filtered_data =
  "../data/cellranger_outputGEO/"

##### Unfiltered data ####
sp_mat_unfiltered = Matrix::readMM(paste0(path_to_raw_data,"matrix_exp1_unfiltered.mtx", sep = ""))
sp_mat_unfiltered %>% class()

# "dgTMatrix"
sp_mat_unfiltered = as(sp_mat_unfiltered, "dgCMatrix")


barcodes =
  read.table(file = paste(path_to_raw_data,
                          "barcodes_exp1_unfiltered.tsv",
                          sep = "/"),
             header = F,
             col.names = "cell_barcode")

colnames(sp_mat_unfiltered) = barcodes$cell_barcode


genes = read.table(file = paste(path_to_raw_data,
                                "features_exp1_unfiltered.tsv",
                                sep = "/"),
                   header = F,
                   sep = "\t",
                   col.names = c("id", "gene_short_name"))

rownames(sp_mat_unfiltered) = genes$id

coldata_unfiltered =
  data.frame(
    cell_id =
      colnames(sp_mat_unfiltered),
    cell_barcode =
      stringr::str_split_fixed(
        colnames(sp_mat_unfiltered),
        pattern = "-",
        n = 2)[,1],
    sample =
      stringr::str_split_fixed(
        colnames(sp_mat_unfiltered),
        pattern = "-",
        n = 2)[,2]
  )

##### Filtered data #####

sp_mat_filtered = Matrix::readMM(paste0(path_to_filtered_data,"matrix_exp1.mtx", sep = ""))
sp_mat_filtered %>% class()

# "dgTMatrix"
sp_mat_filtered = as(sp_mat_filtered, "dgCMatrix")

barcodes_filtered =
  read.table(file = paste(path_to_filtered_data,
                          "barcodes_exp1.tsv",
                          sep = "/"),
             header = F,
             col.names = "cell_barcode")

colnames(sp_mat_filtered) = barcodes_filtered$cell_barcode


genes = read.table(file = paste(path_to_filtered_data,
                                "features_exp1.tsv",
                                sep = "/"),
                   header = F,
                   sep = "\t",
                   col.names = c("id", "gene_short_name"))

rownames(sp_mat_filtered) =
  genes$id

rownames(genes) =
  genes$id

coldata_filtered =
  data.frame(
    cell_id =
      colnames(sp_mat_filtered),
    cell_barcode =
      stringr::str_split_fixed(
        colnames(sp_mat_filtered),
        pattern = "-",
        n = 2)[,1],
    sample =
      stringr::str_split_fixed(
        colnames(sp_mat_filtered),
        pattern = "-",
        n = 2)[,2]
  ) %>%
  mutate(n.umi = Matrix::colSums(sp_mat_filtered)) %>%
  group_by(sample) %>%
  mutate(treshold = min(n.umi)) %>%
  ungroup()

rownames(coldata_filtered) =
  colnames(sp_mat_filtered)

coldata_unfiltered =
  coldata_unfiltered %>%
  left_join(coldata_filtered %>%
              dplyr::select(sample,
                            treshold) %>%
              distinct(),
            by = "sample")
```


### plot knee plot to show cell-free RNA
NB: Sample 3 = normal-appearing cels (200ms)
    Sample 4 = lobulated cells (800ms)

```{r}
ggarrange(plotlist = lapply(unique(coldata_unfiltered$sample), function(this.sample){
  cells_to_pull =
    coldata_unfiltered %>%
    filter(sample == this.sample) %>%
    pull(cell_id)

  data.frame(
    n.umi =
      sp_mat_unfiltered[,cells_to_pull] %>%
      Matrix::colSums()
  ) %>%
    arrange(desc(n.umi)) %>%
    mutate(rank = dplyr::row_number()) %>%
    ggplot() +
    geom_line(aes(x = rank,
                  y = n.umi)) +
    scale_x_log10(breaks = c(1, 3, 10, 30, 100, 300, 1000, 3000, 10000, 30000, 100000)) +
    scale_y_log10(breaks = c(1, 3, 10, 30, 100, 300, 1000, 3000, 10000, 30000, 100000)) +
    theme_bw() +
    geom_hline(yintercept = 1600, color = "firebrick", size = 0.25) +
    geom_hline(yintercept = 10, color = "dodgerblue", size = 0.25)+
    theme(axis.text.x = element_text(angle = 90))+
    xlab("Num Cells") +
    ggtitle(label = paste("Sample ",
                          this.sample,
                          sep = "")
    )

}))


```

Find highly variable genes

```{r}

bg.counts = list()

for (this.sample in (coldata_unfiltered$sample %>% unique)){
  cells_to_pull =
    coldata_unfiltered %>%
    filter(sample == this.sample) %>%
    pull(cell_id)

  curr_mat = sp_mat_unfiltered[,cells_to_pull]
  bg.counts[[this.sample]] =
    curr_mat[,Matrix::colSums(curr_mat) < 10] %>%
    Matrix::rowSums()

}

sapply(X = bg.counts, FUN = length)

sapply(X = bg.counts, FUN = sum)

rm(sp_mat_unfiltered)

cds =
  new_cell_data_set(expression_data = sp_mat_filtered,
                    cell_metadata = coldata_filtered,
                    gene_metadata = genes)

colData(cds)$n.umi=
  Matrix::colSums(counts(cds))

cds = estimate_size_factors(cds)
cds = detect_genes(cds)

# Get highly dispersed genes

dispersion_test <- estimateDispersionsForCellDataSet(cds,
                                                     min_cells_detected = 50,
                                                     removeOutliers = FALSE)
disp_table = dispersionTable(dispersion_test)

ggplot(disp_table) +
  geom_point(aes(x = mean_expression,
                 y = dispersion_empirical),
             alpha = 0.15,
             stroke = 0,
             size = 0.5,
             color = "grey80") +
  geom_point(data =
               disp_table %>%
               filter(mean_expression >= 0.001,
                      dispersion_empirical >= 0.9 * dispersion_fit),
             aes(x = mean_expression,
                 y = dispersion_empirical),
             stroke = 0,
             size = 0.5) +
  monocle_theme_opts() +
  scale_x_log10() +
  scale_y_log10()
```

Get highly dispersed genes

```{r}
ordering_genes =
  disp_table %>%
  filter( mean_expression >= 0.001 & dispersion_empirical >= 0.2 * dispersion_fit) %>%
  pull(gene_id) %>%
  as.character()

length(ordering_genes)
```

Fit the magnitude of a vector whose direction is determined by the cell-free RNA genes

```{r}

#####

num_dim = 50
scaling = T

set.seed(2016)
 
FM <- cds@assays[["counts"]]
# Subset on highly dispersed genes
FM <- FM[rownames(FM) %in% ordering_genes,]


FM <- Matrix::t(Matrix::t(FM)/colData(cds)$Size_Factor)

FM@x = log2(FM@x + 1)

fm_rowsums = Matrix::rowSums(FM)
FM = FM[is.finite(fm_rowsums) & fm_rowsums != 0,]


irlba_res <- monocle3::sparse_prcomp_irlba(x = t(FM),
                                           n = min(num_dim, min(dim(FM)) - 1),
                                           center = scaling,
                                           scale. = scaling)

topDim_pca <- irlba_res$x

FM.t = t(FM)
FM.t.center = Matrix::colMeans(FM.t)

f <- function(i) sqrt(sum((FM.t[, i] - FM.t.center[i])^2)/(nrow(FM.t) - 1L))
FM.t.scale = vapply(seq(ncol(FM.t)), f, pi, USE.NAMES = FALSE)

genes_used = rownames(FM)

norm.bg.counts = list()
for (sample.id in names(bg.counts)) {
  tmp = bg.counts[[sample.id]][genes_used]
  tmp = tmp / (sum(bg.counts[[sample.id]]) / (colData(cds)$n.umi / colData(cds)$Size_Factor)[1])
  norm.bg.counts[[sample.id]] = (tmp - FM.t.center) / FM.t.scale
}

bg.in.pca.space = list()
for (sample.id in names(norm.bg.counts)) {
  bg.in.pca.space[[sample.id]] = as.vector(t(norm.bg.counts[[sample.id]]) %*% irlba_res$rotation)
}

magnitude = function(v) sqrt(sum(v^2))

bg.loadings = list()
for (sample.id in names(bg.in.pca.space)) {
  bg.loadings[[sample.id]] = (topDim_pca %*% as.matrix(bg.in.pca.space[[sample.id]])) /
    magnitude(bg.in.pca.space[[sample.id]])
}

for (sample.id in names(bg.loadings)) {
  colData.colname = paste("bg.loading.", sample.id, sep = "")
  colData(cds)[,colData.colname] = as.vector(bg.loadings[[sample.id]])
}

model_mat_bg = model.matrix(
  formula(paste("~", paste("bg.loading.", names(bg.loadings), sep = "", collapse = " + "))),
  data = as.data.frame(colData(cds)), drop.unused.levels = T)

dim(model_mat_bg)

fit_bg = limma::lmFit(t(topDim_pca), model_mat_bg)

beta_bg = fit_bg$coefficients[, -1, drop = F]
beta_bg[is.na(beta_bg)] = 0

bg_norm_pca = t(t(topDim_pca) - beta_bg %*% t(model_mat_bg[, -1]))

tmp.df = data.frame(
  pca_1 = topDim_pca[, 1],
  pca_2 = topDim_pca[, 2],
  pca_3 = topDim_pca[, 3],
  bg_norm_pca_1 = bg_norm_pca[, 1],
  bg_norm_pca_2 = bg_norm_pca[, 2],
  bg_norm_pca_3 = bg_norm_pca[, 3],
  batch = pData(cds)$sample
)

#########################

cds_bg_remove_no_align =
  preprocess_cds(cds,
                 method = "PCA",
                 num_dim = num_dim,
                 use_genes = ordering_genes)


prev_rownmaes = rownames(cds_bg_remove_no_align@reducedDims[["PCA"]])
prev_colnames = colnames(cds_bg_remove_no_align@reducedDims[["PCA"]])
head(prev_rownmaes)
head(prev_colnames)

cds_bg_remove_no_align@reducedDims[["PCA"]] =
  matrix(bg_norm_pca,ncol = 50)


rownames(cds_bg_remove_no_align@reducedDims[["PCA"]]) = prev_rownmaes
colnames(cds_bg_remove_no_align@reducedDims[["PCA"]]) = prev_colnames



cds_bg_remove_no_align = reduce_dimension(cds_bg_remove_no_align)
cds_bg_remove_no_align = append_umap_coordinates(cds_bg_remove_no_align)

```

See whether it helped.


```{r}
# annotate cells with phenotype
colData(cds_bg_remove_no_align)$pheno = factor('Normal', levels = c('Normal', 'Lobulated', 'Mixed'))
colData(cds_bg_remove_no_align)[which(colData(cds_bg_remove_no_align)$sample == 4 ),'pheno'] = as.factor('Lobulated')

# prep dataframe for UMAP

cds_bg_remove_no_align = reduce_dimension(cds_bg_remove_no_align, reduction_method = 'UMAP', umap.n_neighbors = 30)

# plot
plot_cells(cds_bg_remove_no_align[,which(colData(cds_bg_remove_no_align)$sample %in% c(3,4))], color_cells_by = 'pheno', label_cell_groups = F) + scale_color_manual(values = c('#91bfdb', '#fc8d59')) +
  theme_classic() +
  theme(axis.text=element_text(size=14),
        axis.title=element_text(size=16),
        strip.text.x = element_text(size=16),
        strip.background = element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12)) +
  guides(color=guide_legend(title='Phenotype', override.aes = list(size=5))) # batch effect entirely corrected
```

Load cds exp1

```{r}
# prep phenodata
pd1            <- data.frame(cell = read.csv('../data/cellranger_outputGEO/barcodes_exp1.tsv', sep = '\t', header = F),
                 stringsAsFactors = F)
colnames(pd1)  <- 'cell'

# prep featuredata
fd1            <- as.data.frame(read.csv('../data/cellranger_outputGEO/features_exp1.tsv', sep = '\t', header = F),
                    stringsAsFactors = F)[,c(1,2)]
colnames(fd1)  <- c('id', 'gene_short_name')
row.names(fd1) <- fd1$id

# reannotate phenodata with Seurat
cds_exp1      <- preprocess_seurat(mat_file = '../data/cellranger_outputGEO/matrix_exp1.mtx',
                                  pd = pd1,
                                  fd = fd1)


# annotate cells with phenotype
colData(cds_exp1)$pheno = factor('Normal', levels = c('Normal', 'Lobulated', 'Mixed'))
colData(cds_exp1)[which(colData(cds_exp1)$sample == 4 ),'pheno'] = as.factor('Lobulated')

# plot
plot_cells(cds_exp1, color_cells_by = 'pheno', label_cell_groups = F) + scale_color_manual(values = c('#91bfdb', '#fc8d59')) +
  theme_classic() +
  theme(axis.text=element_text(size=14),
        axis.title=element_text(size=16),
        strip.text.x = element_text(size=16),
        strip.background = element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12)) +
  guides(color=guide_legend(title='Phenotype', override.aes = list(size=5))) # note potential batch effect in taxol treated cells

```


Plot figure 4B

```{r}
SF4B <- ggarrange(plotlist = list(
plot_cells(cds_exp1[,which(colData(cds_exp1)$sample %in% c(3,4))], color_cells_by = 'pheno', label_cell_groups = F) + scale_color_manual(values = c('#91bfdb', '#fc8d59')) +
  theme_classic() +
  theme(axis.title=element_blank(),
        strip.text.x = element_text(size=16),
        strip.background = element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        plot.title = element_text(size = 14, hjust = 0.5)) +
  guides(color=guide_legend(title='Phenotype', override.aes = list(size=5))) +
  ggtitle('Uncorrected\n '),

  plot_cells(cds_bg_remove_no_align[,which(colData(cds_bg_remove_no_align)$sample %in% c(3,4))], color_cells_by = 'pheno', label_cell_groups = F) + scale_color_manual(values = c('#91bfdb', '#fc8d59')) +
  theme_classic() +
  theme(axis.title=element_blank(),
        strip.text.x = element_text(size=16),
        strip.background = element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        plot.title = element_text(size = 14, hjust = 0.5)) +
  guides(color=guide_legend(title='Phenotype', override.aes = list(size=5))) + 
  ggtitle('Corrected for\ncell-free RNA')

), common.legend = T, legend='right'
)

annotate_figure(SF4B,
                left = text_grob('UMAP 2', rot = 90, size = 16),
                bottom = text_grob('UMAP 1', size = 16)
                )

ggsave('SF4B.png', dpi = 900, width = 5.25, height = 2.5)

```

